// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  GetMeData,
  GetMeErrors,
  GetMeResponses,
  HelloData,
  HelloResponses,
  LoginData,
  LoginErrors,
  LoginResponses,
  LogoutData,
  LogoutErrors,
  LogoutResponses,
  RefreshTokenData,
  RefreshTokenErrors,
  RefreshTokenResponses,
  RegisterData,
  RegisterErrors,
  RegisterResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * User login
 *
 * Login with username or email and return access tokens
 */
export const login = <ThrowOnError extends boolean = false>(
  options: Options<LoginData, ThrowOnError>,
) =>
  (options.client ?? client).post<LoginResponses, LoginErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * User logout
 *
 * Invalidate the current session token on the server
 */
export const logout = <ThrowOnError extends boolean = false>(
  options?: Options<LogoutData, ThrowOnError>,
) =>
  (options?.client ?? client).post<LogoutResponses, LogoutErrors, ThrowOnError>(
    {
      responseType: 'json',
      url: '/auth/logout',
      ...options,
    },
  );

/**
 * Get current user information
 *
 * Requires a valid access token in the request header: `Authorization: Bearer <token>`
 */
export const getMe = <ThrowOnError extends boolean = false>(
  options?: Options<GetMeData, ThrowOnError>,
) =>
  (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({
    responseType: 'json',
    url: '/auth/me',
    ...options,
  });

/**
 * Refresh access token
 *
 * Use a refresh token to get new access token and refresh token
 */
export const refreshToken = <ThrowOnError extends boolean = false>(
  options: Options<RefreshTokenData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RefreshTokenResponses,
    RefreshTokenErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/auth/refresh',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * User registration
 *
 * Create a new user account and return access tokens
 */
export const register = <ThrowOnError extends boolean = false>(
  options: Options<RegisterData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    RegisterResponses,
    RegisterErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/auth/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

export const hello = <ThrowOnError extends boolean = false>(
  options?: Options<HelloData, ThrowOnError>,
) =>
  (options?.client ?? client).get<HelloResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/hello',
    ...options,
  });
