// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: 'http://localhost:8080' | (string & {});
};

/**
 * Error response
 */
export type ErrorResponse = {
  /**
   * Error message
   */
  message: string;
};

export type HelloResponse = {
  message: string;
};

/**
 * Login request
 */
export type LoginRequest = {
  /**
   * Username or email
   */
  identifier: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Login response
 */
export type LoginResponse = {
  /**
   * Token pair
   */
  tokens: TokenPair;
  /**
   * User information
   */
  user: UserResponse;
};

/**
 * Refresh token request
 */
export type RefreshTokenRequest = {
  /**
   * Refresh token
   */
  refresh_token: string;
};

/**
 * Refresh token response
 */
export type RefreshTokenResponse = {
  /**
   * New token pair
   */
  tokens: TokenPair;
};

/**
 * Registration request
 */
export type RegisterRequest = {
  /**
   * Email address
   */
  email: string;
  /**
   * Password (at least 8 characters, containing uppercase, lowercase, and digits)
   */
  password: string;
  /**
   * Username (3-50 characters)
   */
  username: string;
};

/**
 * Registration response
 */
export type RegisterResponse = {
  /**
   * Token pair
   */
  tokens: TokenPair;
  /**
   * User information
   */
  user: UserResponse;
};

/**
 * Token pair containing access token and refresh token
 */
export type TokenPair = {
  access_token: string;
  expires_in: number;
  refresh_token: string;
  token_type: string;
};

/**
 * User response
 */
export type UserResponse = {
  /**
   * Creation timestamp
   */
  created_at: string;
  /**
   * Email
   */
  email: string;
  /**
   * User ID
   */
  id: string;
  /**
   * Update timestamp
   */
  updated_at: string;
  /**
   * Username
   */
  username: string;
};

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: '/auth/login';
};

export type LoginErrors = {
  /**
   * Invalid username or password
   */
  401: ErrorResponse;
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * Login successful
   */
  200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/logout';
};

export type LogoutErrors = {
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
  /**
   * Logout successful
   */
  200: ErrorResponse;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/me';
};

export type GetMeErrors = {
  /**
   * Unauthorized
   */
  401: ErrorResponse;
  /**
   * User not found
   */
  404: ErrorResponse;
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
  /**
   * Successfully retrieved user information
   */
  200: UserResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type RefreshTokenData = {
  body: RefreshTokenRequest;
  path?: never;
  query?: never;
  url: '/auth/refresh';
};

export type RefreshTokenErrors = {
  /**
   * Refresh token invalid or expired
   */
  401: ErrorResponse;
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
  /**
   * Token refresh successful
   */
  200: RefreshTokenResponse;
};

export type RefreshTokenResponse2 =
  RefreshTokenResponses[keyof RefreshTokenResponses];

export type RegisterData = {
  body: RegisterRequest;
  path?: never;
  query?: never;
  url: '/auth/register';
};

export type RegisterErrors = {
  /**
   * Invalid request parameters
   */
  400: ErrorResponse;
  /**
   * Username or email already exists
   */
  409: ErrorResponse;
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
  /**
   * Registration successful
   */
  201: RegisterResponse;
};

export type RegisterResponse2 = RegisterResponses[keyof RegisterResponses];

export type HelloData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/hello';
};

export type HelloResponses = {
  /**
   * Successful response
   */
  200: HelloResponse;
};

export type HelloResponse2 = HelloResponses[keyof HelloResponses];

export type Hello2Data = {
  body?: never;
  path?: never;
  query?: never;
  url: '/hello';
};

export type Hello2Responses = {
  /**
   * Successful response
   */
  200: HelloResponse;
};

export type Hello2Response = Hello2Responses[keyof Hello2Responses];
