// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: 'http://localhost:8080' | (string & {});
};

export type ApiResponseEmptyData = {
  code: BusinessCode;
  data: EmptyData;
  message: string;
  timestamp: number;
};

export type ApiResponseHelloResponse = {
  code: BusinessCode;
  data: HelloResponse;
  message: string;
  timestamp: number;
};

export type ApiResponseLoginResponse = {
  code: BusinessCode;
  data: LoginResponse;
  message: string;
  timestamp: number;
};

export type ApiResponseRefreshTokenResponse = {
  code: BusinessCode;
  data: RefreshTokenResponse;
  message: string;
  timestamp: number;
};

export type ApiResponseRegisterResponse = {
  code: BusinessCode;
  data: RegisterResponse;
  message: string;
  timestamp: number;
};

export type ApiResponseUserResponse = {
  code: BusinessCode;
  data: UserResponse;
  message: string;
  timestamp: number;
};

export type BusinessCode = number;

export type BusinessCodes =
  | 19901
  | 10101
  | 10102
  | 10103
  | 10104
  | 10105
  | 10106
  | 10107
  | 10108;

export type EmptyData = {
  [key: string]: unknown;
};

export type ErrorResponse = {
  code: BusinessCode;
  message: string;
  timestamp: number;
};

export type HelloResponse = {
  message: string;
};

/**
 * Login request
 */
export type LoginRequest = {
  /**
   * Username or email
   */
  identifier: string;
  /**
   * Password
   */
  password: string;
};

/**
 * Login response
 */
export type LoginResponse = {
  /**
   * Token pair
   */
  tokens: TokenPair;
  /**
   * User information
   */
  user: UserResponse;
};

/**
 * Refresh token request
 */
export type RefreshTokenRequest = {
  /**
   * Refresh token
   */
  refresh_token: string;
};

/**
 * Refresh token response
 */
export type RefreshTokenResponse = {
  /**
   * New token pair
   */
  tokens: TokenPair;
};

/**
 * Registration request
 */
export type RegisterRequest = {
  /**
   * Email address
   */
  email: string;
  /**
   * Password (at least 8 characters, containing uppercase, lowercase, and digits)
   */
  password: string;
  /**
   * Username (3-50 characters)
   */
  username: string;
};

/**
 * Registration response
 */
export type RegisterResponse = {
  /**
   * Token pair
   */
  tokens: TokenPair;
  /**
   * User information
   */
  user: UserResponse;
};

/**
 * Token pair containing access token and refresh token
 */
export type TokenPair = {
  access_token: string;
  expires_in: number;
  refresh_token: string;
  token_type: string;
};

/**
 * User response
 */
export type UserResponse = {
  /**
   * Creation timestamp
   */
  created_at: string;
  /**
   * Email
   */
  email: string;
  /**
   * User ID
   */
  id: string;
  /**
   * Update timestamp
   */
  updated_at: string;
  /**
   * Username
   */
  username: string;
};

export type LoginData = {
  body: LoginRequest;
  path?: never;
  query?: never;
  url: '/auth/login';
};

export type LoginErrors = {
  /**
   * Invalid credentials
   */
  401: {
    code: BusinessCode;
    message: string;
    timestamp: number;
  };
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
  /**
   * Login successful
   */
  200: ApiResponseLoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type LogoutData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/logout';
};

export type LogoutErrors = {
  /**
   * Unauthorized
   */
  401: {
    code: BusinessCode;
    message: string;
    timestamp: number;
  };
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
  /**
   * Logout successful
   */
  200: ApiResponseEmptyData;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type GetMeData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/auth/me';
};

export type GetMeErrors = {
  /**
   * Unauthorized
   */
  401: {
    code: BusinessCode;
    message: string;
    timestamp: number;
  };
  /**
   * User not found
   */
  404: {
    code: BusinessCode;
    message: string;
    timestamp: number;
  };
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
  /**
   * Successfully retrieved user information
   */
  200: ApiResponseUserResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type RefreshTokenData = {
  body: RefreshTokenRequest;
  path?: never;
  query?: never;
  url: '/auth/refresh';
};

export type RefreshTokenErrors = {
  /**
   * Token invalid or expired
   */
  401: {
    code: BusinessCode;
    message: string;
    timestamp: number;
  };
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type RefreshTokenError = RefreshTokenErrors[keyof RefreshTokenErrors];

export type RefreshTokenResponses = {
  /**
   * Token refresh successful
   */
  200: ApiResponseRefreshTokenResponse;
};

export type RefreshTokenResponse2 =
  RefreshTokenResponses[keyof RefreshTokenResponses];

export type RegisterData = {
  body: RegisterRequest;
  path?: never;
  query?: never;
  url: '/auth/register';
};

export type RegisterErrors = {
  /**
   * Weak password
   */
  400: {
    code: BusinessCode;
    message: string;
    timestamp: number;
  };
  /**
   * Username or email already exists
   */
  409: {
    code: BusinessCode;
    message: string;
    timestamp: number;
  };
  /**
   * Internal server error
   */
  500: ErrorResponse;
};

export type RegisterError = RegisterErrors[keyof RegisterErrors];

export type RegisterResponses = {
  /**
   * Registration successful
   */
  201: ApiResponseRegisterResponse;
};

export type RegisterResponse2 = RegisterResponses[keyof RegisterResponses];

export type HelloData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/hello';
};

export type HelloResponses = {
  /**
   * Successful response
   */
  200: ApiResponseHelloResponse;
};

export type HelloResponse2 = HelloResponses[keyof HelloResponses];
